services:
  - type: web
    name: haven-backend
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "8000"
      - key: MONGO_URL
        value: "mongodb://localhost:27017"
      - key: DB_NAME
        value: "haven"
