"""EXPANDED civic resource catalog — San José / Santa Clara County + State + Federal.

100+ entries covering the entire civic-services map the resident could ever
touch. Every entry has the same shape as `DEMO_RESOURCES` in `seed.py` so it
plugs directly into the map + Find Resources page. Contact fields
(phone, email, website, apply_url, reserve_url) are used by the click-to-
expand modal to power the Call / Email / Apply / Reserve actions.

Sources: sccgov.org, sanjoseca.gov, home.sccgov.org, ca.gov, benefits.gov,
work2future.org, HUD.gov. Data is best-effort accurate as of 2026-Q1 —
in production, this table is replaced by a live sync via the Architect's
"Request Integration OAuth" flow with each partner agency.
"""

CATEGORIES = [
    "shelter", "food", "health", "crisis", "legal", "employment",
    "childcare", "benefits", "reentry", "veterans", "youth", "utility",
    "immigration", "domestic-violence", "mental-health", "substance-use",
    "transportation", "seniors",
]


EXTRA_RESOURCES = [
    # ============================================================ SHELTER / HOUSING
    {"name": "HomeFirst — Sobrato House Youth Center", "type": "shelter", "lat": 37.3316, "lng": -121.9006, "address": "440 N First St, San Jose, CA 95112", "phone": "(408) 380-4550", "website": "https://homefirstscc.org", "apply_url": "https://homefirstscc.org/services", "hours": "24/7", "capacity": 40, "capacity_available": 6, "description": "Transitional housing for youth 18-24 experiencing homelessness.", "eligibility": "Ages 18-24, verified homelessness"},
    {"name": "LifeMoves Julian Street Inn", "type": "shelter", "lat": 37.3437, "lng": -121.8944, "address": "546 W Julian St, San Jose, CA 95110", "phone": "(408) 271-9686", "website": "https://lifemoves.org", "hours": "24/7", "capacity": 75, "capacity_available": 4, "description": "Emergency shelter for single adults with intensive case management.", "eligibility": "Adults, coordinated-entry referral"},
    {"name": "HUD-VASH Voucher Program (VA Palo Alto)", "type": "veterans", "lat": 37.4046, "lng": -122.1479, "address": "3801 Miranda Ave, Palo Alto, CA 94304", "phone": "(650) 493-5000", "website": "https://www.va.gov/homeless/hud-vash.asp", "apply_url": "https://www.va.gov/homeless/apply.asp", "hours": "M–F 8a–4:30p", "description": "HUD-VASH combines HCV rental assistance with VA case management for homeless veterans.", "eligibility": "Veterans experiencing homelessness"},
    {"name": "Here4You Call Center (Coordinated Entry)", "type": "shelter", "lat": 37.3542, "lng": -121.9553, "address": "3180 Newberry Dr, San Jose, CA 95118", "phone": "(408) 385-2400", "website": "https://www.sccgov.org/sites/osh/HomelessServices/Here4You/Pages/home.aspx", "apply_url": "https://homefirstscc.org/here4you", "hours": "M–F 8a–5p", "description": "Single entry point for all Santa Clara County homeless services — housing assessment, prioritization, and placement.", "eligibility": "Any resident experiencing homelessness or at imminent risk"},
    {"name": "Project Homekey — Pavilion Inn Conversion", "type": "shelter", "lat": 37.3541, "lng": -121.8940, "address": "1350 N First St, San Jose, CA 95112", "phone": "(408) 794-1000", "website": "https://www.hcd.ca.gov/grants-and-funding/homekey", "hours": "24/7", "capacity": 90, "capacity_available": 8, "description": "State-funded conversion of motel into 90 interim/permanent supportive housing units.", "eligibility": "Chronically homeless individuals via coordinated entry"},
    {"name": "Bill Wilson Center — Homeless Prevention", "type": "shelter", "lat": 37.3542, "lng": -121.9903, "address": "3490 The Alameda, Santa Clara, CA 95050", "phone": "(408) 243-0222", "website": "https://www.billwilsoncenter.org", "apply_url": "https://www.billwilsoncenter.org/services/homeless_prevention.html", "hours": "M–F 9a–5p", "description": "Rental assistance, back-rent payment, and deposit help to prevent eviction.", "eligibility": "Households at imminent risk of homelessness; income-verified"},
    {"name": "Abode Services — Rapid Rehousing", "type": "shelter", "lat": 37.5485, "lng": -121.9886, "address": "40849 Fremont Blvd, Fremont, CA 94538", "phone": "(510) 657-7409", "website": "https://www.abodeservices.org", "apply_url": "https://www.abodeservices.org/get-help", "hours": "M–F 8a–5p", "description": "Rapid rehousing subsidies for families and individuals moving from shelter to permanent housing.", "eligibility": "Currently homeless, income under 30% AMI"},
    {"name": "PATH San Jose (People Assisting the Homeless)", "type": "shelter", "lat": 37.3387, "lng": -121.8853, "address": "1601 The Alameda, San Jose, CA 95126", "phone": "(408) 641-4114", "website": "https://epath.org", "hours": "M–F 8a–4p", "description": "Street outreach, housing navigation, and interim housing placement.", "eligibility": "People living unsheltered"},
    {"name": "InnVision Shelter Network — Georgia Travis House", "type": "shelter", "lat": 37.3428, "lng": -121.9026, "address": "260 Commercial St, San Jose, CA 95112", "phone": "(408) 271-9700", "website": "https://lifemoves.org", "hours": "24/7", "capacity": 60, "capacity_available": 3, "description": "Emergency shelter for families with children.", "eligibility": "Families with dependent children"},
    {"name": "Santa Clara County Office of Supportive Housing", "type": "shelter", "lat": 37.3591, "lng": -121.9075, "address": "3180 Newberry Dr, San Jose, CA 95118", "phone": "(408) 794-1000", "website": "https://osh.sccgov.org", "hours": "M–F 8a–5p", "description": "County department overseeing all supportive-housing programs, Section 8 admin, and Homekey pipeline.", "eligibility": "Varies by program"},
    {"name": "Housing Authority of Santa Clara County", "type": "shelter", "lat": 37.3226, "lng": -121.9078, "address": "505 W Julian St, San Jose, CA 95110", "phone": "(408) 275-8770", "website": "https://www.scchousingauthority.org", "apply_url": "https://www.scchousingauthority.org/apply", "hours": "M–F 8a–5p", "description": "Administers Section 8 Housing Choice Voucher and Public Housing programs.", "eligibility": "Income under 50% AMI"},

    # ============================================================ FOOD
    {"name": "Second Harvest of Silicon Valley — Food Connection", "type": "food", "lat": 37.4130, "lng": -121.9376, "address": "4001 N First St, San Jose, CA 95134", "phone": "(800) 984-3663", "website": "https://www.shfb.org", "apply_url": "https://www.shfb.org/get-food", "hours": "M–F 8a–5p", "description": "Free groceries via 900+ pantry partners across Santa Clara & San Mateo Counties. Call for nearest site.", "eligibility": "No verification required"},
    {"name": "CalFresh (SNAP) Enrollment — Santa Clara County SSA", "type": "benefits", "lat": 37.3505, "lng": -121.8971, "address": "1867 Senter Rd, San Jose, CA 95112", "phone": "(408) 758-3800", "website": "https://socialservices.sccgov.org/food-assistance", "apply_url": "https://www.getcalfresh.org", "hours": "M–F 8a–5p", "description": "Apply for CalFresh (California SNAP) — monthly grocery benefits on an EBT card.", "eligibility": "Income under 200% FPL"},
    {"name": "WIC — Santa Clara County", "type": "food", "lat": 37.3395, "lng": -121.9082, "address": "1755 The Alameda, San Jose, CA 95126", "phone": "(408) 792-5101", "website": "https://phd.sccgov.org/wic", "apply_url": "https://myfamily.wic.ca.gov", "hours": "M–F 8a–5p", "description": "Women, Infants, Children nutrition program — checks + nutrition classes for pregnant women and kids under 5.", "eligibility": "Pregnant/postpartum women, kids under 5, income under 185% FPL"},
    {"name": "Loaves & Fishes — Winchester Kitchen", "type": "food", "lat": 37.3306, "lng": -121.8873, "address": "1101 S Winchester Blvd, San Jose, CA 95128", "phone": "(408) 998-1500", "website": "https://loavesfishes.org", "hours": "M–F 12p–1p (hot meals)", "description": "Free hot meals served daily, no questions asked. Also operates a mobile meal truck.", "eligibility": "Open to anyone"},
    {"name": "St. Joseph's Family Center", "type": "food", "lat": 37.0058, "lng": -121.5680, "address": "7950 Church St, Gilroy, CA 95020", "phone": "(408) 842-6662", "website": "https://sjfcgilroy.org", "hours": "M–F 9a–4p", "description": "Food pantry, rental assistance, and family support in South County.", "eligibility": "Gilroy/San Martin/Morgan Hill residents"},
    {"name": "Martha's Kitchen", "type": "food", "lat": 37.3117, "lng": -121.8779, "address": "311 Willow St, San Jose, CA 95110", "phone": "(408) 293-6111", "website": "https://marthas-kitchen.org", "hours": "M/W/F 4:30p–5:30p", "description": "Free hot meals + grocery bags; volunteer-run since 1981.", "eligibility": "Open to anyone"},

    # ============================================================ HEALTH
    {"name": "Medi-Cal Enrollment — Covered California", "type": "benefits", "lat": 37.3382, "lng": -121.8863, "address": "1867 Senter Rd, San Jose, CA 95112", "phone": "(800) 300-1506", "website": "https://www.dhcs.ca.gov/services/medi-cal", "apply_url": "https://www.coveredca.com", "hours": "M–F 8a–8p", "description": "California's Medicaid program — free/low-cost health coverage. Enroll anytime through Covered California.", "eligibility": "Income under 138% FPL (adults) or 266% (kids)"},
    {"name": "Valley Homeless Healthcare Program — Backstreet Clinic", "type": "health", "lat": 37.3382, "lng": -121.8863, "address": "278 N 2nd St, San Jose, CA 95112", "phone": "(408) 977-1840", "website": "https://www.scvmc.org", "hours": "M–F 8a–5p", "description": "Free medical, dental, mental-health, and substance-use services for people experiencing homelessness.", "eligibility": "No insurance / ID required"},
    {"name": "Gardner Family Health Network", "type": "health", "lat": 37.3184, "lng": -121.8776, "address": "195 E Virginia St, San Jose, CA 95112", "phone": "(408) 918-2680", "website": "https://gardnerhealth.com", "apply_url": "https://gardnerhealth.com/become-a-patient", "hours": "M–Sat varies", "description": "Federally Qualified Health Center — primary care, dental, behavioral health, WIC, on sliding-scale fees.", "eligibility": "Open to all, no insurance required"},
    {"name": "Santa Clara Valley Medical Center — Downtown Clinic", "type": "health", "lat": 37.3145, "lng": -121.9058, "address": "751 S Bascom Ave, San Jose, CA 95128", "phone": "(408) 885-5000", "website": "https://www.scvmc.org", "hours": "24/7 ER", "description": "County safety-net hospital; ER, primary care, specialty clinics.", "eligibility": "All patients; sliding scale available"},
    {"name": "Bay Area Community Health — East San Jose", "type": "health", "lat": 37.3547, "lng": -121.8259, "address": "270 Tully Rd, San Jose, CA 95111", "phone": "(408) 729-9700", "website": "https://www.bach.health", "hours": "M–Sat 8a–5p", "description": "FQHC — primary care, dental, mental health, pediatrics, on sliding-scale.", "eligibility": "Open to all"},
    {"name": "Mental Health Urgent Care — EMQ FamiliesFirst", "type": "mental-health", "lat": 37.3346, "lng": -121.8899, "address": "251 Llewellyn Ave, Campbell, CA 95008", "phone": "(408) 379-3796", "website": "https://mymhurgentcare.org", "hours": "24/7", "description": "Walk-in mental-health crisis services for children, teens, and families.", "eligibility": "Anyone in mental-health crisis"},

    # ============================================================ CRISIS
    {"name": "Santa Clara County Suicide & Crisis Hotline", "type": "crisis", "lat": 37.3382, "lng": -121.8863, "address": "Countywide (phone)", "phone": "(855) 278-4204", "website": "https://www.sccgov.org/sites/mhd", "hours": "24/7", "description": "24/7 hotline for anyone in mental-health crisis, or friends/family seeking help.", "eligibility": "Anyone"},
    {"name": "988 Suicide & Crisis Lifeline", "type": "crisis", "lat": 37.3382, "lng": -121.8863, "address": "Nationwide (phone)", "phone": "988", "website": "https://988lifeline.org", "hours": "24/7", "description": "National 3-digit crisis line — call or text 988.", "eligibility": "Anyone in crisis"},
    {"name": "Next Door Solutions to Domestic Violence", "type": "domestic-violence", "lat": 37.3390, "lng": -121.8918, "address": "234 E Gish Rd, San Jose, CA 95112", "phone": "(408) 279-2962", "website": "https://www.nextdoorsolutions.org", "hours": "24/7", "description": "24/7 crisis line, emergency shelter, court advocacy for DV survivors.", "eligibility": "Anyone experiencing intimate-partner violence"},
    {"name": "Community Solutions — SafeSpace Program", "type": "domestic-violence", "lat": 37.1305, "lng": -121.6544, "address": "16264 Church St, Morgan Hill, CA 95037", "phone": "(408) 683-4118", "website": "https://www.communitysolutions.org", "hours": "24/7", "description": "DV shelter, therapy, legal advocacy across South County.", "eligibility": "DV survivors and children"},
    {"name": "Bill Wilson Center — Youth Crisis Line", "type": "crisis", "lat": 37.3542, "lng": -121.9903, "address": "3490 The Alameda, Santa Clara, CA 95050", "phone": "(408) 850-6125", "website": "https://www.billwilsoncenter.org", "hours": "24/7", "description": "Runaway and youth-crisis hotline + shelter (ages 11-17).", "eligibility": "Youth ages 11-17 and their families"},

    # ============================================================ EMPLOYMENT / JOB TRAINING
    {"name": "work2future — San Jose Career Center", "type": "employment", "lat": 37.3186, "lng": -121.9430, "address": "1601 Foxworthy Ave, San Jose, CA 95118", "phone": "(408) 794-1150", "website": "https://www.work2future.biz", "apply_url": "https://www.work2future.biz/individuals", "hours": "M–F 8a–5p", "description": "Free job search, resume, training, and placement services (WIOA-funded).", "eligibility": "Adults 18+ seeking work; TANF/UI/dislocated priority"},
    {"name": "work2future — Reentry Career Services", "type": "reentry", "lat": 37.3542, "lng": -121.8975, "address": "151 W Mission St, San Jose, CA 95110", "phone": "(408) 794-1200", "website": "https://www.work2future.biz/reentry-services", "hours": "M–F 8a–5p", "description": "Specialized job training and placement for formerly incarcerated individuals.", "eligibility": "Individuals with criminal history"},
    {"name": "Santa Clara County Reentry Resource Center", "type": "reentry", "lat": 37.3541, "lng": -121.8940, "address": "151 W Mission St, San Jose, CA 95110", "phone": "(408) 535-4260", "website": "https://www.sccgov.org/sites/oreentry", "hours": "M–F 8a–5p", "description": "One-stop reentry services — housing, employment, health, ID recovery, mentoring.", "eligibility": "Anyone with recent incarceration history"},
    {"name": "Goodwill Silicon Valley — Job Connection Center", "type": "employment", "lat": 37.3319, "lng": -121.9040, "address": "1080 N 7th St, San Jose, CA 95112", "phone": "(408) 998-5774", "website": "https://www.goodwillsv.org", "apply_url": "https://www.goodwillsv.org/find-a-job", "hours": "M–F 8a–5p", "description": "Free job coaching, digital literacy, forklift/computer training.", "eligibility": "Open to job seekers"},
    {"name": "California EDD — Unemployment Insurance", "type": "benefits", "lat": 37.3382, "lng": -121.8863, "address": "1601 Foxworthy Ave, San Jose, CA 95118", "phone": "(800) 300-5616", "website": "https://edd.ca.gov", "apply_url": "https://edd.ca.gov/en/unemployment", "hours": "24/7 online", "description": "File for California Unemployment Insurance and Disability Insurance.", "eligibility": "Workers who lost job through no fault of their own"},

    # ============================================================ BENEFITS / CASH AID
    {"name": "CalWORKs — Santa Clara County SSA", "type": "benefits", "lat": 37.3505, "lng": -121.8971, "address": "1867 Senter Rd, San Jose, CA 95112", "phone": "(408) 758-3800", "website": "https://socialservices.sccgov.org/CalWORKs", "apply_url": "https://benefitscal.com", "hours": "M–F 8a–5p", "description": "TANF cash aid + job services for families with children.", "eligibility": "Families with kids under 18, income under limits"},
    {"name": "General Assistance (GA) — Santa Clara County", "type": "benefits", "lat": 37.3505, "lng": -121.8971, "address": "1867 Senter Rd, San Jose, CA 95112", "phone": "(408) 758-3800", "website": "https://socialservices.sccgov.org/general-assistance", "apply_url": "https://benefitscal.com", "hours": "M–F 8a–5p", "description": "County-funded cash aid for adults without dependent children.", "eligibility": "Adults, income under limits, no other cash aid"},
    {"name": "Social Security — San Jose Field Office", "type": "benefits", "lat": 37.3141, "lng": -121.9081, "address": "80 Great Oaks Blvd, San Jose, CA 95119", "phone": "(866) 964-3971", "website": "https://www.ssa.gov", "apply_url": "https://www.ssa.gov/apply", "hours": "M–F 9a–4p", "description": "Retirement, SSDI, SSI, and Medicare enrollment.", "eligibility": "Varies by program"},

    # ============================================================ LEGAL
    {"name": "Law Foundation of Silicon Valley — Housing Program", "type": "legal", "lat": 37.3389, "lng": -121.8863, "address": "4 N Second St, Suite 1300, San Jose, CA 95113", "phone": "(408) 280-2416", "website": "https://www.lawfoundation.org", "apply_url": "https://www.lawfoundation.org/get-help", "hours": "M–F 9a–5p", "description": "Free legal help — eviction defense, immigration, education advocacy, mental-health rights.", "eligibility": "Income under 200% FPL"},
    {"name": "Katharine & George Alexander Community Law Center (Santa Clara Law)", "type": "legal", "lat": 37.3527, "lng": -121.9426, "address": "1030 Ruff Dr, San Jose, CA 95110", "phone": "(408) 288-7030", "website": "https://law.scu.edu/kgaclc", "hours": "M–F 9a–5p", "description": "Free legal clinics on immigration, workers rights, tax, and consumer issues.", "eligibility": "Low income; income screening required"},
    {"name": "Santa Clara County Public Defender", "type": "legal", "lat": 37.3541, "lng": -121.8940, "address": "120 W Mission St, San Jose, CA 95110", "phone": "(408) 299-7700", "website": "https://www.sccgov.org/sites/pdo", "hours": "M–F 8a–5p", "description": "Criminal defense, record clearance (PC 1203.4), Clean Slate program.", "eligibility": "Financial eligibility for criminal cases; open for record clearance"},

    # ============================================================ IMMIGRATION
    {"name": "SIREN — Services, Immigrant Rights & Education Network", "type": "immigration", "lat": 37.3387, "lng": -121.8853, "address": "1425 Koll Cir #103, San Jose, CA 95112", "phone": "(408) 453-3003", "website": "https://siren-bayarea.org", "hours": "M–F 9a–5p", "description": "Immigration legal services, DACA renewals, naturalization, know-your-rights training.", "eligibility": "Immigrants and their families"},
    {"name": "Catholic Charities of Santa Clara — Immigration Legal Services", "type": "immigration", "lat": 37.3216, "lng": -121.9040, "address": "2625 Zanker Rd, San Jose, CA 95134", "phone": "(408) 468-0100", "website": "https://catholiccharitiesscc.org", "hours": "M–F 9a–5p", "description": "Full-service immigration legal help — asylum, family petitions, naturalization.", "eligibility": "Low-income immigrants"},

    # ============================================================ UTILITY / FINANCIAL
    {"name": "LIHEAP (Low-Income Home Energy Assistance) — Sacred Heart", "type": "utility", "lat": 37.3211, "lng": -121.8748, "address": "1381 South 1st St, San Jose, CA", "phone": "(408) 278-2160", "website": "https://www.csd.ca.gov/energy-help", "apply_url": "https://sacredheartcs.org/services/apply-for-liheap", "hours": "M–F 9a–4p", "description": "One-time utility bill payment help for low-income households.", "eligibility": "Household income under 60% state median"},
    {"name": "PG&E CARE Program", "type": "utility", "lat": 37.3382, "lng": -121.8863, "address": "Statewide (phone/online)", "phone": "(866) 743-2273", "website": "https://www.pge.com/care", "apply_url": "https://www.pge.com/care", "hours": "24/7 online", "description": "20% discount on PG&E electric + gas bills for income-qualified households.", "eligibility": "Income under 200% FPL"},

    # ============================================================ CHILDCARE / YOUTH
    {"name": "4Cs of Santa Clara County (Community Child Care Council)", "type": "childcare", "lat": 37.3411, "lng": -121.8944, "address": "1655 De La Cruz Blvd #100, Santa Clara, CA 95050", "phone": "(669) 212-0007", "website": "https://www.4c-scc.org", "apply_url": "https://www.4c-scc.org/parents", "hours": "M–F 8a–5p", "description": "Subsidized childcare vouchers, provider directory, referrals.", "eligibility": "Working parents; income-based subsidy"},
    {"name": "First 5 Santa Clara County", "type": "childcare", "lat": 37.3641, "lng": -121.9075, "address": "4000 Moorpark Ave #200, San Jose, CA 95117", "phone": "(408) 260-3700", "website": "https://www.first5kids.org", "hours": "M–F 8a–5p", "description": "Early-childhood programs, home visiting, developmental screenings.", "eligibility": "Families with kids 0-5"},
    {"name": "Boys & Girls Clubs of Silicon Valley", "type": "youth", "lat": 37.3227, "lng": -121.8880, "address": "1141 N 4th St, San Jose, CA 95112", "phone": "(408) 971-2432", "website": "https://bgclubsv.org", "hours": "M–F 2p–8p", "description": "After-school programs, mentoring, sports, and college prep for youth 6-18.", "eligibility": "Youth ages 6-18"},
    {"name": "SJPD PAL (Police Activities League)", "type": "youth", "lat": 37.3315, "lng": -121.8926, "address": "680 Park Ave, San Jose, CA 95110", "phone": "(408) 794-1600", "website": "https://sjpal.org", "hours": "M–F 3p–8p", "description": "Youth sports, mentoring, and academic support run by SJPD officers.", "eligibility": "Youth ages 5-18"},

    # ============================================================ SUBSTANCE USE
    {"name": "Gateway — Substance Use Access & Referral", "type": "substance-use", "lat": 37.3341, "lng": -121.8956, "address": "976 Lenzen Ave, San Jose, CA 95126", "phone": "(800) 488-9919", "website": "https://www.sccgov.org/sites/bhd/Pages/Gateway.aspx", "hours": "M–F 8a–6p", "description": "County single point of entry for substance-use treatment, MAT, and detox referrals.", "eligibility": "Anyone seeking SUD treatment"},
    {"name": "HAVEN Society Inc.", "type": "substance-use", "lat": 37.3336, "lng": -121.8930, "address": "1659 Scott Blvd #1, Santa Clara, CA 95050", "phone": "(408) 244-1834", "website": "https://www.pathwaysociety.org", "hours": "M–F 8a–5p", "description": "Outpatient SUD counseling, DUI programs, MAT.", "eligibility": "Adults with substance-use concerns"},

    # ============================================================ SENIORS
    {"name": "Sourcewise — Aging & Adult Services", "type": "seniors", "lat": 37.3527, "lng": -121.9426, "address": "2115 The Alameda, San Jose, CA 95126", "phone": "(408) 350-3200", "website": "https://www.mysourcewise.com", "hours": "M–F 8a–5p", "description": "Senior nutrition, care management, IHSS, Medicare counseling.", "eligibility": "Adults 60+ and their caregivers"},
    {"name": "In-Home Supportive Services (IHSS) — Santa Clara County", "type": "seniors", "lat": 37.3505, "lng": -121.8971, "address": "353 W Julian St, San Jose, CA 95110", "phone": "(408) 792-1600", "website": "https://socialservices.sccgov.org/ihss", "apply_url": "https://socialservices.sccgov.org/ihss/apply", "hours": "M–F 8a–5p", "description": "Paid caregiver services for elderly, blind, or disabled residents.", "eligibility": "Medi-Cal recipients with functional needs"},

    # ============================================================ TRANSPORTATION
    {"name": "VTA Access Paratransit", "type": "transportation", "lat": 37.3327, "lng": -121.9033, "address": "3331 N First St, San Jose, CA 95134", "phone": "(408) 321-2380", "website": "https://www.vta.org/access", "apply_url": "https://www.vta.org/access-eligibility", "hours": "M–F 8a–5p", "description": "Door-to-door transit for riders with disabilities.", "eligibility": "ADA-eligible riders"},
    {"name": "VTA Lifeline Reduced-Fare Program", "type": "transportation", "lat": 37.3327, "lng": -121.9033, "address": "3331 N First St, San Jose, CA 95134", "phone": "(408) 321-2300", "website": "https://www.vta.org/go/fares/reduced", "hours": "M–F 8a–5p", "description": "Discounted transit passes for low-income riders.", "eligibility": "Income under 200% FPL"},

    # ============================================================ FEDERAL DIRECT
    {"name": "HUD San Francisco Field Office", "type": "shelter", "lat": 37.7783, "lng": -122.4207, "address": "One Sansome St #1200, San Francisco, CA 94104", "phone": "(415) 489-6400", "website": "https://www.hud.gov/states/california/renting/hawebsites", "hours": "M–F 8a–5p", "description": "Federal HUD regional office — Fair Housing complaints, Section 8, VASH policy.", "eligibility": "Varies"},
    {"name": "VA Palo Alto Health Care System — Homeless Program", "type": "veterans", "lat": 37.4046, "lng": -122.1479, "address": "3801 Miranda Ave, Palo Alto, CA 94304", "phone": "(650) 493-5000 x66393", "website": "https://www.paloalto.va.gov/services/homeless.asp", "hours": "M–F 8a–4:30p", "description": "VA homeless veteran outreach, HCHV, Grant & Per Diem programs.", "eligibility": "Veterans"},
    {"name": "211 Bay Area (Get Connected)", "type": "crisis", "lat": 37.3382, "lng": -121.8863, "address": "Countywide (phone)", "phone": "211", "website": "https://211bayarea.org", "hours": "24/7", "description": "24/7 free info + referrals for housing, food, health, and human services.", "eligibility": "Anyone"},

    # ============================================================ MENTAL HEALTH
    {"name": "Santa Clara County Behavioral Health Call Center", "type": "mental-health", "lat": 37.3230, "lng": -121.9080, "address": "828 S Bascom Ave, San Jose, CA 95128", "phone": "(800) 704-0900", "website": "https://bhsd.sccgov.org", "hours": "24/7", "description": "Gateway to county mental-health services — screening, referrals, urgent care.", "eligibility": "County residents; Medi-Cal or uninsured"},
    {"name": "Momentum for Health — Adult Services", "type": "mental-health", "lat": 37.3272, "lng": -121.9358, "address": "438 N White Rd, San Jose, CA 95127", "phone": "(408) 254-6828", "website": "https://momentumforhealth.org", "hours": "M–F 8a–5p", "description": "Outpatient therapy, crisis residential, and supported housing for serious mental illness.", "eligibility": "Adults with SMI; Medi-Cal accepted"},
    {"name": "Bill Wilson Center — Centre for Living with Dying", "type": "mental-health", "lat": 37.3542, "lng": -121.9901, "address": "3490 The Alameda, Santa Clara, CA 95050", "phone": "(408) 243-0222", "website": "https://www.billwilsoncenter.org/services/all/cld.html", "hours": "M–F 9a–5p", "description": "Grief and trauma support for adults and children at no cost.", "eligibility": "Anyone experiencing grief/trauma"},
    {"name": "Uplift Family Services — Crisis Stabilization", "type": "mental-health", "lat": 37.3057, "lng": -121.8865, "address": "251 Llewellyn Ave, Campbell, CA 95008", "phone": "(408) 379-3790", "website": "https://upliftfs.org", "hours": "24/7", "description": "Mobile crisis team + short-term stabilization for youth in mental-health crisis.", "eligibility": "Youth under 21"},

    # ============================================================ SUBSTANCE USE
    {"name": "Gardner Health — South County Recovery", "type": "substance-use", "lat": 37.0057, "lng": -121.5683, "address": "7526 Monterey St, Gilroy, CA 95020", "phone": "(408) 842-6445", "website": "https://gardnerhealthservices.org", "hours": "M–F 8a–5p", "description": "Outpatient SUD counseling, MAT referrals, and bilingual recovery groups.", "eligibility": "Medi-Cal or sliding scale"},
    {"name": "Horizon Services — Mission Street Sobering Center", "type": "substance-use", "lat": 37.3494, "lng": -121.9058, "address": "2101 Alexian Dr, San Jose, CA 95116", "phone": "(408) 254-6550", "website": "https://horizonservices.org", "hours": "24/7", "description": "Safe sobering beds and warm-handoff to detox and residential treatment.", "eligibility": "Adults under the influence needing a safe place"},
    {"name": "National Alliance for Drug Endangered Children Helpline", "type": "substance-use", "lat": 37.3382, "lng": -121.8850, "address": "Countywide (phone)", "phone": "(800) 662-4357", "website": "https://www.samhsa.gov/find-help/national-helpline", "hours": "24/7", "description": "SAMHSA national helpline — free, confidential treatment referral in English/Spanish.", "eligibility": "Anyone"},

    # ============================================================ DOMESTIC VIOLENCE
    {"name": "Maitri — South Asian Survivor Services", "type": "domestic-violence", "lat": 37.3541, "lng": -121.9552, "address": "PO Box 697, Santa Clara, CA 95052", "phone": "(888) 862-4874", "website": "https://maitri.org", "hours": "M–F 9a–5p helpline", "description": "Culturally responsive DV support, transitional housing, and legal advocacy for South Asian survivors.", "eligibility": "DV survivors; all welcome"},
    {"name": "YWCA Golden Gate Silicon Valley — Support Services", "type": "domestic-violence", "lat": 37.3320, "lng": -121.8994, "address": "375 S Third St, San Jose, CA 95112", "phone": "(800) 572-2782", "website": "https://yourywca.org", "hours": "24/7 crisis line", "description": "Rape crisis center, DV shelter, therapy, and human-trafficking survivor services.", "eligibility": "Survivors of DV, sexual assault, trafficking"},
    {"name": "Community Solutions — La Isla Pacífica Shelter", "type": "domestic-violence", "lat": 37.0083, "lng": -121.5760, "address": "9015 Murray Ave #100, Gilroy, CA 95020", "phone": "(877) 363-7238", "website": "https://communitysolutions.org", "hours": "24/7", "description": "Confidential South County DV emergency shelter with bilingual advocates.", "eligibility": "DV survivors and children"},

    # ============================================================ FOOD (EXPANDED)
    {"name": "West Valley Community Services — Food Market", "type": "food", "lat": 37.3168, "lng": -122.0225, "address": "10104 Vista Dr, Cupertino, CA 95014", "phone": "(408) 255-8033", "website": "https://wvcommunityservices.org", "hours": "M–F 10a–4p", "description": "Client-choice food market, rent assistance, and case management for West Valley residents.", "eligibility": "West Valley residents; income-verified"},
    {"name": "CityTeam San Jose — Community Meals", "type": "food", "lat": 37.3268, "lng": -121.8830, "address": "1174 Old Bayshore Hwy, San Jose, CA 95112", "phone": "(408) 288-2160", "website": "https://www.cityteam.org/san-jose", "hours": "Daily 5:30p dinner", "description": "Daily free dinner, food pantry boxes, and hygiene supplies.", "eligibility": "Anyone"},
    {"name": "Sacred Heart Community Service — Food Pantry", "type": "food", "lat": 37.3155, "lng": -121.8888, "address": "1381 S First St, San Jose, CA 95110", "phone": "(408) 278-2160", "website": "https://sacredheartcs.org", "apply_url": "https://sacredheartcs.org/gethelp", "hours": "M–F 9a–4p", "description": "Weekly grocery pickup, clothes closet, and essential-needs assistance.", "eligibility": "Santa Clara County residents; self-attestation"},
    {"name": "St. Justin Community Ministry Food Pantry", "type": "food", "lat": 37.3524, "lng": -121.9985, "address": "2655 Homestead Rd, Santa Clara, CA 95051", "phone": "(408) 296-4310", "website": "https://stjustinministry.org", "hours": "T/Th 9a–11:30a", "description": "Weekly grocery bags including fresh produce and dairy.", "eligibility": "No documentation required"},
    {"name": "Village Harvest — Gleaning Program", "type": "food", "lat": 37.3230, "lng": -121.9500, "address": "Countywide (mobile)", "phone": "(888) 378-4841", "website": "https://villageharvest.org", "hours": "Varies", "description": "Harvested backyard fruit distributed free through partner pantries.", "eligibility": "Via partner agencies"},
    {"name": "Salvation Army San Jose — Emmanuel House Meals", "type": "food", "lat": 37.3492, "lng": -121.9026, "address": "405 N Fourth St, San Jose, CA 95112", "phone": "(408) 282-1165", "website": "https://sanjose.salvationarmy.org", "hours": "Daily breakfast + dinner", "description": "Daily meals, food boxes, and seasonal assistance.", "eligibility": "Anyone"},
    {"name": "Senior Nutrition Program — Meals on Wheels SCC", "type": "seniors", "lat": 37.3535, "lng": -121.9265, "address": "1650 Senter Rd, San Jose, CA 95112", "phone": "(408) 350-3246", "website": "https://www.sourcewise.org/meals-on-wheels", "apply_url": "https://www.sourcewise.org", "hours": "M–F 8a–5p", "description": "Home-delivered meals for homebound seniors.", "eligibility": "60+, homebound"},
    {"name": "Hunger at Home — Prepared Meal Rescue", "type": "food", "lat": 37.3708, "lng": -121.9220, "address": "1560 Berger Dr, San Jose, CA 95112", "phone": "(408) 763-8151", "website": "https://hungerathome.org", "hours": "M–F 9a–5p", "description": "Rescued banquet-quality meals redistributed to shelters and nonprofits.", "eligibility": "Via partner shelters"},

    # ============================================================ HEALTH (EXPANDED)
    {"name": "Valley Health Center Downtown San Jose", "type": "health", "lat": 37.3346, "lng": -121.8927, "address": "777 E Santa Clara St, San Jose, CA 95112", "phone": "(408) 977-4550", "website": "https://scvmc.scvh.org", "apply_url": "https://www.vhcnetwork.org", "hours": "M–F 8a–5p", "description": "Full primary care, dental, pharmacy — county safety-net clinic.", "eligibility": "Medi-Cal, uninsured, sliding scale"},
    {"name": "Gardner Health Services — St. James Health Center", "type": "health", "lat": 37.3487, "lng": -121.8951, "address": "55 E Julian St, San Jose, CA 95112", "phone": "(408) 918-2600", "website": "https://gardnerhealthservices.org", "hours": "M–F 8a–5p", "description": "FQHC primary care, behavioral health, and WIC on-site.", "eligibility": "All patients regardless of ability to pay"},
    {"name": "RotaCare Free Clinic — San Jose", "type": "health", "lat": 37.3113, "lng": -121.8583, "address": "2011 Little Orchard St, San Jose, CA 95125", "phone": "(408) 918-2650", "website": "https://rotacarebayarea.org", "hours": "T/Th evenings", "description": "Completely free urgent + chronic care for uninsured adults.", "eligibility": "Uninsured, income-qualified"},
    {"name": "School Health Clinics of Santa Clara County", "type": "health", "lat": 37.2967, "lng": -121.8189, "address": "3030 Alum Rock Ave, San Jose, CA 95127", "phone": "(408) 937-3600", "website": "https://schoolhealthclinics.org", "hours": "M–F 8a–5p", "description": "Pediatric + family care based at school campuses; immunizations and sports physicals.", "eligibility": "Children + families; no one turned away"},
    {"name": "Planned Parenthood Mar Monte — San Jose Central", "type": "health", "lat": 37.3221, "lng": -121.9021, "address": "1691 The Alameda, San Jose, CA 95126", "phone": "(408) 287-7526", "website": "https://www.plannedparenthood.org", "hours": "M–Sa", "description": "Reproductive health, STI testing, gender-affirming care — sliding scale.", "eligibility": "Anyone; Family PACT accepted"},
    {"name": "Santa Clara County Dental Clinic — Valley Specialty", "type": "health", "lat": 37.3126, "lng": -121.9345, "address": "751 S Bascom Ave, San Jose, CA 95128", "phone": "(408) 885-4400", "website": "https://scvmc.scvh.org/hospitals-clinics", "hours": "M–F 8a–5p", "description": "Emergency and restorative dental for Medi-Cal and uninsured patients.", "eligibility": "Medi-Cal Dental or sliding scale"},

    # ============================================================ CRISIS (EXPANDED)
    {"name": "988 Suicide & Crisis Lifeline — Santa Clara", "type": "crisis", "lat": 37.3382, "lng": -121.8860, "address": "Countywide (phone/text)", "phone": "988", "website": "https://988lifeline.org", "hours": "24/7", "description": "Call or text 988 — immediate crisis counseling and mobile-team dispatch.", "eligibility": "Anyone"},
    {"name": "Community Crisis Response Team (TRUST)", "type": "crisis", "lat": 37.3382, "lng": -121.8900, "address": "Countywide (mobile)", "phone": "(408) 539-4119", "website": "https://trustsantaclaracounty.org", "hours": "24/7", "description": "Non-police mobile crisis response for mental-health and substance-use emergencies.", "eligibility": "Anyone in Santa Clara County"},

    # ============================================================ YOUTH (EXPANDED)
    {"name": "Bill Wilson Center — Drop-In Center for Youth", "type": "youth", "lat": 37.3363, "lng": -121.8907, "address": "693 S Second St, San Jose, CA 95112", "phone": "(408) 925-0231", "website": "https://www.billwilsoncenter.org/services/all/drop-in.html", "hours": "M–F 10a–6p", "description": "Showers, laundry, meals, case management for youth 13–25 on the street.", "eligibility": "Ages 13–25"},
    {"name": "The LGBTQ Youth Space", "type": "youth", "lat": 37.3327, "lng": -121.8917, "address": "452 S First St, San Jose, CA 95113", "phone": "(408) 343-7940", "website": "https://youthspace.org", "hours": "T–F 3p–9p", "description": "Community + mental-health drop-in for LGBTQ+ youth and young adults 13–25.", "eligibility": "LGBTQ+ ages 13–25"},
    {"name": "Fresh Lifelines for Youth (FLY)", "type": "youth", "lat": 37.3897, "lng": -121.8955, "address": "568 Valley Way, Milpitas, CA 95035", "phone": "(408) 263-2630", "website": "https://flyprogram.org", "hours": "M–F 9a–5p", "description": "Legal education, leadership training, and mentoring for justice-involved youth.", "eligibility": "Youth 11–24 touched by juvenile-justice system"},
    {"name": "Unity Care — Transitional Housing for Foster Youth", "type": "youth", "lat": 37.3239, "lng": -121.9107, "address": "1400 Parkmoor Ave #115, San Jose, CA 95126", "phone": "(408) 971-9822", "website": "https://unitycare.org", "hours": "M–F 9a–5p", "description": "THP-Plus housing and life-skills coaching for former foster youth.", "eligibility": "Former foster youth 18–24"},

    # ============================================================ EMPLOYMENT (EXPANDED)
    {"name": "Goodwill of Silicon Valley — Career Navigation", "type": "employment", "lat": 37.3238, "lng": -121.9026, "address": "1080 N Seventh St, San Jose, CA 95112", "phone": "(408) 998-5774", "website": "https://goodwillsv.org", "hours": "M–F 8a–5p", "description": "Job coaching, paid work experience, and re-entry employment tracks.", "eligibility": "Barriers to employment; walk-ins OK"},
    {"name": "ConXión to Community — Workforce Development", "type": "employment", "lat": 37.3050, "lng": -121.8613, "address": "749 Story Rd #10, San Jose, CA 95122", "phone": "(408) 213-0961", "website": "https://cxtc.org", "hours": "M–F 9a–5p", "description": "Vocational training, GED prep, and youth workforce programs — bilingual.", "eligibility": "Low-income residents"},
    {"name": "Downtown Streets Team — San Jose", "type": "employment", "lat": 37.3352, "lng": -121.8890, "address": "80 S Market St, San Jose, CA 95113", "phone": "(408) 917-1691", "website": "https://streetsteam.org", "hours": "M–F 9a–5p", "description": "Volunteer beautification work in exchange for basic-needs stipends + job placement for unhoused members.", "eligibility": "People experiencing homelessness"},
    {"name": "Center for Employment Training (CET) San Jose", "type": "employment", "lat": 37.3159, "lng": -121.8703, "address": "701 Vine St, San Jose, CA 95110", "phone": "(408) 287-7924", "website": "https://cetweb.edu", "apply_url": "https://cetweb.edu/apply", "hours": "M–F 8a–5p", "description": "Hands-on skills training (HVAC, medical assistant, culinary) with job placement.", "eligibility": "Open enrollment; financial aid available"},

    # ============================================================ CHILDCARE (EXPANDED)
    {"name": "Choices for Children — Subsidy Programs", "type": "childcare", "lat": 37.3082, "lng": -121.9017, "address": "1484 Saratoga Ave, San Jose, CA 95129", "phone": "(408) 297-3295", "website": "https://choicesforchildren.org", "hours": "M–F 8:30a–5p", "description": "Childcare payment assistance and licensed-provider referrals.", "eligibility": "Income-qualified working families"},
    {"name": "Head Start / Early Head Start — SCC Office of Education", "type": "childcare", "lat": 37.3672, "lng": -121.9264, "address": "1290 Ridder Park Dr, San Jose, CA 95131", "phone": "(408) 453-6900", "website": "https://www.sccoe.org/headstart", "apply_url": "https://www.sccoe.org/headstart/Pages/apply.aspx", "hours": "M–F 8a–5p", "description": "Free preschool + family services for children 0–5.", "eligibility": "Income under 100% FPL, foster, or homeless children"},

    # ============================================================ SENIORS (EXPANDED)
    {"name": "The Health Trust — Senior Connections", "type": "seniors", "lat": 37.2455, "lng": -121.8863, "address": "3180 Newberry Dr #200, San Jose, CA 95118", "phone": "(408) 513-8700", "website": "https://healthtrust.org", "hours": "M–F 9a–5p", "description": "Case management, friendly visitors, and fall-prevention for isolated seniors.", "eligibility": "60+"},
    {"name": "Alzheimer's Association Northern California Helpline", "type": "seniors", "lat": 37.3382, "lng": -121.8870, "address": "Countywide (phone)", "phone": "(800) 272-3900", "website": "https://www.alz.org/norcal", "hours": "24/7", "description": "Dementia care consultation, respite referrals, caregiver support groups.", "eligibility": "Anyone affected by dementia"},

    # ============================================================ VETERANS (EXPANDED)
    {"name": "Santa Clara County Office of Veterans Services", "type": "veterans", "lat": 37.3131, "lng": -121.8859, "address": "68 N Winchester Blvd, Santa Clara, CA 95050", "phone": "(408) 918-4980", "website": "https://vso.sccgov.org", "hours": "M–F 8a–5p", "description": "Free help filing VA claims, benefits appeals, and discharge upgrades.", "eligibility": "Veterans + dependents"},

    # ============================================================ LEGAL (EXPANDED)
    {"name": "Bay Area Legal Aid — San Jose Office", "type": "legal", "lat": 37.3505, "lng": -121.9051, "address": "4 N Second St #600, San Jose, CA 95113", "phone": "(800) 551-5554", "website": "https://baylegal.org", "hours": "M–F 9a–5p", "description": "Free civil legal help — housing, benefits denials, DV restraining orders.", "eligibility": "Income under 125% FPL"},
    {"name": "Pro Bono Project Silicon Valley", "type": "legal", "lat": 37.3348, "lng": -121.8925, "address": "480 N First St #219, San Jose, CA 95112", "phone": "(408) 998-5298", "website": "https://probonoproject.org", "hours": "M–F 9a–5p", "description": "Volunteer attorneys for family law, guardianship, and record clearance.", "eligibility": "Low-income county residents"},
    {"name": "Santa Clara County Self-Help Center (Court)", "type": "legal", "lat": 37.3527, "lng": -121.9016, "address": "201 N First St, San Jose, CA 95113", "phone": "(408) 882-2926", "website": "https://www.scscourt.org/self_help", "hours": "M–F 8:30a–3p", "description": "Free court-form help — evictions, fee waivers, name changes, small claims.", "eligibility": "Self-represented litigants"},

    # ============================================================ TRANSPORTATION (EXPANDED)
    {"name": "OUTREACH Paratransit + Senior Transportation", "type": "transportation", "lat": 37.3040, "lng": -121.8664, "address": "926 Rock Ave #10, San Jose, CA 95131", "phone": "(408) 436-2865", "website": "https://outreach1.org", "hours": "M–F 8a–5p", "description": "Door-to-door rides for seniors and riders with disabilities; guaranteed-ride programs.", "eligibility": "Seniors 65+, ADA-eligible riders"},

    # ============================================================ BENEFITS (EXPANDED)
    {"name": "Medi-Cal Enrollment — SSA Assistance Application Center", "type": "benefits", "lat": 37.3505, "lng": -121.8969, "address": "1867 Senter Rd, San Jose, CA 95112", "phone": "(408) 758-3800", "website": "https://socialservices.sccgov.org/medi-cal", "apply_url": "https://benefitscal.com", "hours": "M–F 8a–5p", "description": "Apply for free/low-cost Medi-Cal health coverage.", "eligibility": "Income under 138% FPL"},
    {"name": "Covered California Storefront — San Jose", "type": "benefits", "lat": 37.3220, "lng": -121.8845, "address": "2114 Senter Rd #26, San Jose, CA 95112", "phone": "(800) 300-1506", "website": "https://www.coveredca.com", "apply_url": "https://apply.coveredca.com", "hours": "M–F 9a–5p", "description": "In-person help choosing subsidized health plans.", "eligibility": "CA residents without employer coverage"},
    {"name": "SparkPoint Financial Coaching — United Way Bay Area", "type": "benefits", "lat": 37.3350, "lng": -121.8905, "address": "1400 Parkmoor Ave #250, San Jose, CA 95126", "phone": "(408) 345-4300", "website": "https://uwba.org/sparkpoint", "hours": "M–F 9a–5p", "description": "Free financial coaching, credit repair, and benefits screening (one-stop).", "eligibility": "Anyone; focus on low-income households"},

    # ============================================================ SHELTER (EXPANDED)
    {"name": "Gilroy Compassion Center — Day Center", "type": "shelter", "lat": 37.0100, "lng": -121.5726, "address": "370 Tomkins Ct, Gilroy, CA 95020", "phone": "(408) 763-7120", "website": "https://gilroycompassioncenter.org", "hours": "M–F 9a–3p", "description": "South County day shelter — showers, mail, storage, housing navigation.", "eligibility": "Anyone unhoused in South County"},
    {"name": "Amigos de Guadalupe — Rent Relief & Navigation", "type": "shelter", "lat": 37.3506, "lng": -121.8535, "address": "1897 Alum Rock Ave #35, San Jose, CA 95116", "phone": "(408) 341-6069", "website": "https://amigosdeguadalupe.org", "hours": "M–F 9a–5p", "description": "East San José rent relief, eviction defense navigation, and family services.", "eligibility": "East SJ residents at risk of displacement"},
]
